from enum import StrEnum


class ErrorCode(StrEnum):
    PAPER_NOT_FOUND = "PAPER_NOT_FOUND"
    INVALID_DOI = "INVALID_DOI"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    EXTRACTION_TIMEOUT = "EXTRACTION_TIMEOUT"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    DUPLICATE_DOI = "DUPLICATE_DOI"
    NO_FILE = "NO_FILE"
    PAPER_FILE_MISSING = "PAPER_FILE_MISSING"
