from enum import StrEnum


class ErrorCode(StrEnum):
    CLAUDE_TIMEOUT = "CLAUDE_TIMEOUT"
    CLAUDE_ERROR = "CLAUDE_ERROR"
    CLAUDE_PARSE_ERROR = "CLAUDE_PARSE_ERROR"
    INVALID_STATE = "INVALID_STATE"
    TOO_MANY_CONNECTIONS = "TOO_MANY_CONNECTIONS"
