from enum import StrEnum


class ErrorCode(StrEnum):
    CLAUDE_TIMEOUT = "CLAUDE_TIMEOUT"
    CLAUDE_ERROR = "CLAUDE_ERROR"
    CLAUDE_PARSE_ERROR = "CLAUDE_PARSE_ERROR"
    INVALID_STATE = "INVALID_STATE"
    INVALID_STEP = "INVALID_STEP"
    STEP_NOT_IN_ERROR = "STEP_NOT_IN_ERROR"
    RETRY_PRECONDITION_FAILED = "RETRY_PRECONDITION_FAILED"
    TOO_MANY_CONNECTIONS = "TOO_MANY_CONNECTIONS"
